cors:
  originPatterns: http//localhost8080,http//localhost3000,https://well.com.br
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_spring_boot_well?useTimezone=True&serveTimezone=UTC
    username: root
    password: Wellsql28.
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
springdoc: 
  pathsToMatch:  /api/**/v1/**
  swagger-ui:
    use-root-path: true
    